apiVersion: v1
kind: PersistentVolume

metadata:
  name: notes-db-volume
  labels:
    type: local
  namespace: db
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "<Path to your data directory>"

---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: notes-db-pvc
  namespace: db
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
